packages/perennial-vault/contracts/Vault.sol
packages/perennial-vault/contracts/lib/StrategyLib.sol

Adds `.adjust()` to each instance of a pending position being read in the vault to properly read the position value.
Fixes: https://github.com/sherlock-audit/2023-09-perennial-judging/issues/55.

[Fix] Properly adjust positions in Vault calculations

---

packages/perennial-vault/contracts/Vault.sol
packages/perennial-vault/test/integration/vault/Vault.test.ts

Fixes: https://github.com/sherlock-audit/2023-09-perennial-judging/issues/29.

[Fix] settlementFee skipped on no-op updates when totalClaimable is zero in Vault

---

packages/perennial/contracts/types/Order.sol
packages/perennial/test/unit/types/Order.test.ts

Fixes: https://github.com/sherlock-audit/2023-09-perennial-judging/issues/62.

[Fix] Order.liquidityCheckApplicable() logic

---

packages/perennial-extensions/contracts/MultiInvoker.sol

Updates closableAmount initialization logic to match that in `Market`.

[Fix] closableAmount initialization in MultiInvoker

---

packages/common/tsconfig.default.json
packages/perennial-deploy/hardhat.config.ts
packages/perennial-deploy/package.json
packages/perennial-deploy/tasks/commitPrice.ts
packages/perennial-deploy/tasks/index.ts
packages/perennial-deploy/tasks/verifyProxies.ts
yarn.lock

Etherscan has an API to link proxies to impls rather than doing it manually - since we use proxies fairly heavily this task just pulls all contracts that are proxies are requests Etherscan to link them to our expected impl
Also adds a task to commit a price for a given feed ID

Add verify-proxies, commit-price hardhat tasks

---

packages/perennial-vault/contracts/Vault.sol
packages/perennial-vault/contracts/interfaces/IVault.sol
packages/perennial-vault/contracts/lib/StrategyLib.sol
packages/perennial-vault/test/integration/vault/Vault.test.ts

Consolidates and de-duplicates context loading between the core vault flow and the strategy flow.
- Saves `~105k` gas on update.
- Removes `41` LoC from Vault.
- Removes `525 bytes` code size from Vault.

De-duplicate context loading in Vault

---

packages/perennial/contracts/Market.sol
packages/perennial/test/unit/market/Market.test.ts

Relaxes the `MarketStalePriceError` invariant to allow two new cases:
- Don't check for stale price when the account has no position (both latest & current are empty).
- Don't check for stale price when the position is unchanged, and the collateral is either also unchanged or depositing.
Relaxes the `MarketOperatorNotAllowedError` invariant to allow one new case:
- Allow anyone to deposit zero-or-more into any account with no position change.
- Zero amount constitutes a settlement, while non-zero can be used for resolving shortfall.
- Note: Previously this did not allow depositing on-behalf outside of shortfall resolution.

Relax invariant

---

packages/perennial/contracts/types/Version.sol
packages/perennial/test/unit/market/Market.test.ts

Resolves: https://github.com/sherlock-audit/2023-10-perennial-judging/issues/57.

[Fix] Cap funding skew at 100%

---

packages/perennial/contracts/types/Order.sol
packages/perennial/test/integration/core/fees.test.ts

Temporarily resolves: https://github.com/sherlock-audit/2023-10-perennial-judging/issues/58, while we design a more holistic algorithm.

[Fix] Make fees nonnegative

---

packages/perennial-vault/contracts/Vault.sol
packages/perennial-vault/contracts/interfaces/IVault.sol
packages/perennial-vault/contracts/lib/StrategyLib.sol
packages/perennial-vault/test/integration/vault/Vault.test.ts

Resolves: https://github.com/sherlock-audit/2023-10-perennial-judging/issues/29.

[Fix] Use allocate for max redeem calculation

---

packages/perennial/contracts/Market.sol
packages/perennial/contracts/interfaces/IMarket.sol
packages/perennial/test/integration/core/liquidate.test.ts
packages/perennial/test/unit/market/Market.test.ts

Adds local awareness of the pending open amount, in addition to the existing pending close amount.
This partially resolves: https://github.com/sherlock-audit/2023-10-perennial-judging/issues/24, by providing better worst case position size for margin calculation.
Additionally this resolves: https://github.com/sherlock-audit/2023-10-perennial-judging/issues/23, by using margin for all pending position instead of maintenance. Maintenance is now *only* used to determine whether the latest position is liquidatable.

[Fix] Add pendingOpen

---

packages/perennial-extensions/test/integration/helpers/setupHelpers.ts
packages/perennial-vault/contracts/Vault.sol
packages/perennial/contracts/Market.sol
packages/perennial/contracts/interfaces/IMarket.sol
packages/perennial/contracts/types/Version.sol
packages/perennial/test/integration/core/happyPath.test.ts
packages/perennial/test/integration/helpers/setupHelpers.ts
packages/perennial/test/unit/market/Market.test.ts
packages/perennial/test/unit/types/Version.test.ts

The reward system has not yet been turned on since launch, so there are no reward balances within the system that need to be kept track of for backwards compatibility. This system takes up considerably code complexity within the protocol, and is a good candidate for removal, since we've determined more efficient ways to achieve the same incentivization goals.
For this first pass, we will only remove the minimum changeset required to statifies our codesize requirements, optimizing for least criticial codepaths first.
- Removes the `reward()` token getter and setter so that the reward token cannot be set.
- Removes the `claimReward()` function since there are no reward, and can no longer be any rewards, in the system.
- Removes the `_accumulateReward()` function within `Version` since there …

v2.1 codesize

---

packages/perennial-extensions/test/integration/core/Orders.test.ts
packages/perennial-extensions/test/integration/helpers/setupHelpers.ts
packages/perennial-vault/contracts/Vault.sol
packages/perennial-vault/contracts/interfaces/IVault.sol
packages/perennial-vault/contracts/lib/StrategyLib.sol
packages/perennial-vault/contracts/types/Registration.sol
packages/perennial-vault/test/integration/vault/Vault.test.ts

- Adds an invariant that vault weights must sum up to `UFixed6Lib.ONE` (and therefore represent percentages).
- Vault weights must be reset to satisfy this variant prior to upgrade.

Vault weight sum to one

---

packages/perennial-vault/test/integration/vault/Vault.test.ts
packages/perennial/contracts/Market.sol
packages/perennial/contracts/types/Order.sol
packages/perennial/test/integration/core/closedProduct.test.ts
packages/perennial/test/integration/core/happyPath.test.ts
packages/perennial/test/unit/market/Market.test.ts

- Properly hooks up the local implementation of `Order` storage from: https://github.com/equilibria-xyz/perennial-v2/pull/208.
- Removes order simplification when opening and closing two orders in a single version
- Records opening and closing separately along with total order count.
- No longer can open an close or open and switch sides during a single current version.

[Fix] Use local order

---

packages/perennial-oracle/contracts/keeper/KeeperOracle.sol
packages/perennial-vault/contracts/lib/StrategyLib.sol
packages/perennial/contracts/Market.sol
packages/perennial/contracts/interfaces/IOracleProvider.sol
packages/perennial/contracts/test/GlobalTester.sol
packages/perennial/contracts/types/Global.sol
packages/perennial/test/unit/market/Market.test.ts
packages/perennial/test/unit/types/Global.test.ts

Moves the `latestPrice` handling from the Market to the Oracle latest by ensure the Oracle keeps track of and returns the correct `latestPrice` in the event of an invalid version.
`latest()` must return a valid version on all oracles before upgrading.

[Cleanup] Remove latestPrice from Market

---

packages/perennial-vault/contracts/types/VaultParameter.sol
packages/perennial/contracts/types/Global.sol
packages/perennial/contracts/types/MarketParameter.sol
packages/perennial/contracts/types/Order.sol
packages/perennial/contracts/types/Position.sol
packages/perennial/contracts/types/ProtocolParameter.sol
packages/perennial/contracts/types/RiskParameter.sol

Adds warnings to each storage struct that change slot count due to it being used at the top-level of a contract.
- Removes extra unneeded slot introduced in: https://github.com/equilibria-xyz/perennial-v2/pull/208.
- Leaves the additional slot in `RiskParameter` similarly introduced as a follow-up.

[Docs] Add storage expansion warnings

---

packages/perennial/contracts/Market.sol
packages/perennial/contracts/interfaces/IMarket.sol
packages/perennial/test/integration/core/happyPath.test.ts
packages/perennial/test/unit/market/Market.test.ts

`Order` type now includes the timestamp internally.

[Cleanup] Remove timestamp from OrderCreated event

---

packages/perennial/contracts/Market.sol
packages/perennial/contracts/interfaces/IMarket.sol
packages/perennial/contracts/types/Order.sol

Moves `latestVersion` and `latestCheckpoint` into the settlement context so that they only need to be loaded from storage once.

[Cleanup] Only load Version / Checkpoint once

---

packages/common/testutil/types.ts
packages/perennial-vault/test/integration/vault/Vault.test.ts
packages/perennial/contracts/Market.sol
packages/perennial/contracts/test/CheckpointTester.sol
packages/perennial/contracts/test/LocalTester.sol
packages/perennial/contracts/types/Checkpoint.sol
packages/perennial/contracts/types/Global.sol
packages/perennial/contracts/types/Local.sol
packages/perennial/contracts/types/Order.sol
packages/perennial/test/integration/core/closedProduct.test.ts
packages/perennial/test/integration/core/liquidate.test.ts
packages/perennial/test/unit/market/Market.test.ts
packages/perennial/test/unit/types/Checkpoint.test.ts
packages/perennial/test/unit/types/Local.test.ts
packages/perennial/test/unit/types/Position.test.ts
packages/perennial/test/unit/types/Version.test.ts

- Adds a `1-bit` protection semaphore to the `Order`
- Account-level protection can be access via pending `Order`

[Cleanup] Add order protection

---

packages/common/testutil/types.ts
packages/perennial-vault/test/integration/vault/Vault.test.ts
packages/perennial/contracts/Market.sol
packages/perennial/contracts/interfaces/IMarket.sol
packages/perennial/contracts/test/GlobalTester.sol
packages/perennial/contracts/types/Global.sol
packages/perennial/contracts/types/Local.sol
packages/perennial/test/integration/core/liquidate.test.ts
packages/perennial/test/unit/market/Market.test.ts
packages/perennial/test/unit/types/Global.test.ts
packages/perennial/test/unit/types/Local.test.ts
packages/perennial/test/unit/types/Version.test.ts

In the new checkpoint system, `_credit` directly incrementing an out-of-path account's collateral creates an out-of-sync balance.
This creates a separate `claimable` balance on a `Local` to store liquidation fees, and any future off-path fees like interface fees.
Similarly this creates a separate `exposure` account on the `Global` instead of using `account(0)'s` collateral as the spillover for adiabatic exposure.

[Fix] _credit incrementing collateral

---

package.json
packages/common/testutil/types.ts
packages/perennial-vault/test/integration/vault/Vault.test.ts
packages/perennial/contracts/Market.sol
packages/perennial/contracts/types/Checkpoint.sol
packages/perennial/contracts/types/Order.sol
packages/perennial/contracts/types/Version.sol
packages/perennial/test/integration/core/fees.test.ts
packages/perennial/test/integration/core/happyPath.test.ts
packages/perennial/test/unit/market/Market.test.ts
packages/perennial/test/unit/types/Checkpoint.test.ts
packages/perennial/test/unit/types/Version.test.ts
yarn.lock

So that we can have `linear / proportiona / adiabatic`-level logic in the `Checkpoint`.

[Cleanup] Split tradeFee in Version

---

packages/perennial/contracts/types/Local.sol

Fixes the storage definition for `Local` from one slot to two.
This does not have any effect on the underlying logic, but should maintain consistency for readability.

[Docs] Fix local slots

---

packages/common/testutil/types.ts
packages/perennial/test/integration/core/fees.test.ts
packages/perennial/test/integration/core/happyPath.test.ts
packages/perennial/test/unit/market/Market.test.ts

A market incurs exposure when it enters a state in which taker imbalance is not covered by maker liquidity.  This state cannot be archieved by opening/closing positions; an undercollateralized maker must be liquidated to arrive at this state.  This change extends the global assertion wrapper to cover `exposure`, and adds two tests:
- Updating risk parameters to add adiabatic fees after a maker is liquidated
- Liquidating a maker in a market where adiabatic fees have already been established

Market tests for exposure when maker is zero

---

packages/perennial/contracts/Market.sol
packages/perennial/contracts/interfaces/IMarket.sol
packages/perennial/contracts/types/Local.sol
packages/perennial/test/unit/market/Market.test.ts

- Removed slot 1 from `Local` storage
- Eliminate loading of collateral data from `Local` into new `Checkpoint`
- Eliminate `Market::updateOracle()`
Slot 0 unchanged.  Slot 1 was deprecated in 2.2, where it was updated to write 0's.  Slot 1 is now eliminated.
Facility introduced in 2.2 to initialize `Checkpoint` with collateral from `Local` has been removed.  **Must go into no-order mode and settle all users prior to deployment.**

Remove v2.2 migration code

---

packages/perennial/test/integration/core/fees.test.ts
packages/perennial/test/integration/core/happyPath.test.ts
packages/perennial/test/integration/core/liquidate.test.ts
packages/perennial/test/integration/helpers/setupHelpers.ts

**Changes**
- Update existing settle helper to actually call `settle`, which was new for 2.2.
- Introduce new `updateNoOp` helper replacing the old call.  Use it in places where changes to position IDs would be confusing.
- Fix issue with interest and funding fee tests, which were only looking at the first emitted event of the desired type.  Use a map-reduce solution to parse and aggregate desired fields from events.

Update settle unit test helper

---

packages/perennial/contracts/Market.sol
packages/perennial/contracts/libs/CheckpointLib.sol
packages/perennial/contracts/libs/VersionLib.sol
packages/perennial/contracts/test/IntentTester.sol
packages/perennial/contracts/test/VersionTester.sol
packages/perennial/contracts/types/Intent.sol
packages/perennial/test/unit/types/Intent.test.ts
packages/perennial/test/unit/types/Version.test.ts

Hooks up the special-case fee processing logic to Checkpoint and Version internally for intent orders.
- allow for settlementFee to be skipped for takers
- skip linear / proportional / adiabatic fees
Does not enable subtractive / market fees on intent orders.

Add intent order fee logic

---

.github/workflows/CI.yml
packages/perennial-oracle/contracts/keeper/KeeperOracle.sol

One-liner, as this does not impact unit tests.  Will need to plan redeployment of `KeeperOracle`s accordingly.

[v2.1.1 Audit Fix] KeeperOracle to settle using market.settle instead of no-op update

---

packages/perennial-vault/contracts/types/Checkpoint.sol
packages/perennial-vault/test/integration/vault/Vault.test.ts
packages/perennial-vault/test/unit/types/Account.test.ts
packages/perennial-vault/test/unit/types/Checkpoint.test.ts

Splits the order count tracking in the Vault checkpoints into separate deposit and redeem counts. This allows us to split the global settlement fee for the id properly between deposits and redemptions.
Resolves https://github.com/sherlock-audit/2024-02-perennial-v2-3-judging/issues/26.
- Splits `Checkpoint.orders` into `Checkpoint.deposits` and `Checkpoint.redemptions`
- The settle-only migration step will ensure that all legacy checkpoints have been read before switching to the new format

[v2.2 Audit Fix] Split global settlement fee between deposits and redemptions

---

packages/perennial-oracle/contracts/keeper/KeeperOracle.sol
packages/perennial-oracle/contracts/keeper/types/Price.sol
packages/perennial-oracle/contracts/test/PriceTester.sol
packages/perennial-oracle/test/unit/oracle/KeeperOracle.test.ts
packages/perennial-oracle/test/unit/pyth/PythOracleFactory.test.ts
packages/perennial-oracle/test/unit/types/Price.test.ts
packages/perennial/contracts/Market.sol

- Establish unit tests for covering `KeeperOracle` without focusing on a specific (Pyth/Chainlink) implementation.
- Reproduce [audit issue](https://github.com/sherlock-audit/2024-02-perennial-v2-3-judging/issues/6) handling of expired prices.
- Resolve by storing a validity flag alongside price.
- Clean up redundant initialization logic in `PythOracleFactory.test.ts` (unrelated).
`KeeperFactory` and `KeeperOracle` and  instances will need to be redeployed.  Suspect this was already part of the 2.1 -> 2.2 migration plan.

[v2.2 Audit Fix] KeeperOracle flag to trap invalid oracle versions

---

packages/perennial-vault/contracts/Vault.sol
packages/perennial-vault/contracts/lib/StrategyLib.sol
packages/perennial-vault/test/integration/vault/Vault.test.ts

Resolves: https://github.com/sherlock-audit/2024-02-perennial-v2-3-judging/issues/11.
Adds additional documentation on what is going on in this calculation and why we do not need to the second `.add(withdrawal)`.

[v2.2 Audit Fix] Resolves double-subtraction issue with asset ineligibility calculation

---

packages/perennial-extensions/test/helpers/types.ts
packages/perennial-extensions/test/integration/core/Orders.test.ts
packages/perennial-extensions/test/unit/MultiInvoker/MultiInvoker.test.ts
packages/perennial-vault/contracts/lib/StrategyLib.sol
packages/perennial-vault/test/integration/vault/Vault.test.ts

- Fix for [issue 17](https://github.com/sherlock-audit/2024-02-perennial-v2-3-judging/issues/17) - When _StrategyLib_ loaded strategy context, it was loading the vault's position rather than the marketwide position.
- Resolved some linting errors (unrelated).

[v2.2 Audit Fix] Fix Vault bug loading strategy context

---

.github/workflows/CI.yml
packages/perennial/contracts/Market.sol
packages/perennial/contracts/MarketFactory.sol
packages/perennial/contracts/interfaces/IMarket.sol
packages/perennial/contracts/interfaces/IMarketFactory.sol
packages/perennial/contracts/libs/InvariantLib.sol
packages/perennial/test/unit/market/Market.test.ts
packages/perennial/test/unit/marketfactory/MarketFactory.test.ts

Adds `signer` role in parallel to `operator` that a user can assign to their account. Like operators, there can be many signers on one account, and signers can be revoked at any time.
A signer is able to sign messages on behalf of the user.

Add delegated signing

---

packages/perennial-extensions/test/integration/helpers/setupHelpers.ts
packages/perennial-oracle/test/integration/metaquants/MetaQuantsOracleFactory.test.ts
packages/perennial-oracle/test/integration/pyth/PythOracleFactory.test.ts
packages/perennial-oracle/test/integrationSepolia/chainlink/ChainlinkOracleFactory.test.ts
packages/perennial-verifier/contracts/Verifier.sol
packages/perennial-verifier/contracts/interfaces/IVerifier.sol
packages/perennial-verifier/contracts/types/OperatorUpdate.sol
packages/perennial-verifier/test/helpers/erc712.ts
packages/perennial-verifier/test/unit/Verifier/Verifier.ts
packages/perennial/contracts/MarketFactory.sol
packages/perennial/contracts/interfaces/IMarketFactory.sol
packages/perennial/test/integration/helpers/setupHelpers.ts
packages/perennial/test/unit/marketfactory/MarketFactory.test.ts

Adds a second version of `MarketFactory.updateOperator()` that takes a signed message from the account instead of assuming the sender is the account.

Add updateOperatorWithSignature

---

packages/perennial-extensions/contracts/Coordinator.sol
packages/perennial-extensions/test/integration/helpers/setupHelpers.ts
packages/perennial-oracle/test/integration/metaquants/MetaQuantsOracleFactory.test.ts
packages/perennial-oracle/test/integration/pyth/PythOracleFactory.test.ts
packages/perennial-oracle/test/integrationSepolia/chainlink/ChainlinkOracleFactory.test.ts
packages/perennial-vault/test/integration/helpers/setupHelpers.ts
packages/perennial-vault/test/integration/vault/Vault.test.ts
packages/perennial/contracts/Market.sol
packages/perennial/contracts/interfaces/IMarket.sol
packages/perennial/test/integration/core/fees.test.ts
packages/perennial/test/integration/core/happyPath.test.ts
packages/perennial/test/integration/helpers/setupHelpers.ts
packages/perennial/test/unit/market/Market.test.ts

Updates `updateRiskParameter()` to be compatible with our v2.2 migration flow by surfacing a `isMigration` flag which overrides the latestRiskParameter read with an empty read (w/ zero adiabatic fee), only setting the scale to avoid a divide-by-zero error.
Also updates the `Coordinator` for this new interface.
Cannot add a backwards compatible overload of the `updateRiskParameter` due to code size constraints.

[v2.2] Make updateRiskParameter migration-safe

---

packages/perennial-extensions/contracts/MultiInvoker.sol

Uses `settle` instead of `update` in the execute order function in the MultiInvoker
https://github.com/sherlock-audit/2024-05-kwenta-x-perennial-integration-update-judging/issues/34

[Delegate MultiInvoker Audit Fix] Use 'settle' instead of noOp 'update' in MultiInvoker

---

packages/common/testutil/types.ts
packages/perennial-verifier/contracts/types/Fill.sol
packages/perennial-verifier/contracts/types/Intent.sol
packages/perennial-verifier/test/helpers/erc712.ts
packages/perennial-verifier/test/unit/Verifier/Verifier.ts
packages/perennial/contracts/Market.sol
packages/perennial/contracts/MarketFactory.sol
packages/perennial/contracts/interfaces/IMarket.sol
packages/perennial/contracts/interfaces/IMarketFactory.sol
packages/perennial/contracts/libs/CheckpointLib.sol
packages/perennial/contracts/test/GuaranteeTester.sol
packages/perennial/contracts/types/Guarantee.sol
packages/perennial/contracts/types/Order.sol
packages/perennial/contracts/types/ProtocolParameter.sol
packages/perennial/test/unit/market/Market.test.ts
packages/perennial/test/unit/marketfactory/MarketFactory.test.ts
packages/perennial/test/unit/types/Guarantee.test.ts
packages/perennial/test/unit/types/Local.test.ts
packages/perennial/test/unit/types/Version.test.ts

Adds a `solver` fee to intents.
Updates the `Intent` message to contain three new fields:
- `originator` the originator of the order (ex. the interface)
- receives the subtractive fee less the solver fee
- `solver` the solver of the guarentee (ex. router API)
- receives the solver fee
- `fee` portion of the subtractive fee to instead give to the solver.
All referral information is now read from the intent instead of passed in as a parameter to `update()`.

Add solver fee

---

packages/common/testutil/types.ts
packages/perennial/contracts/Market.sol
packages/perennial/contracts/libs/CheckpointLib.sol
packages/perennial/contracts/libs/VersionLib.sol
packages/perennial/contracts/test/GuaranteeTester.sol
packages/perennial/contracts/types/Guarantee.sol
packages/perennial/test/unit/market/Market.test.ts
packages/perennial/test/unit/types/Guarantee.test.ts
packages/perennial/test/unit/types/Version.test.ts

Updates the intent fill logic to only charge the `takerFee` (and it's associated sub-fees) to the maker side of the intent order pair during a fill.

Only charge taker fees to the maker side of the intent order

---

packages/perennial-extensions/test/integration/core/Orders.test.ts
packages/perennial/contracts/Market.sol
packages/perennial/contracts/interfaces/IMarket.sol
packages/perennial/test/integration/core/fees.test.ts
packages/perennial/test/integration/core/happyPath.test.ts
packages/perennial/test/integration/core/liquidate.test.ts
packages/perennial/test/unit/market/Market.test.ts

- Removes `Updated` event
- Adds `Guarantee` to the `OrderCreated` event
- We will add `referrer`, `liquidator`, and `solver` to `OrderCreated` in a future task due to in progress issues.

Remove Updated event

---

packages/perennial/contracts/Market.sol
packages/perennial/contracts/MarketFactory.sol
packages/perennial/contracts/interfaces/IMarket.sol
packages/perennial/contracts/interfaces/IMarketFactory.sol
packages/perennial/contracts/types/ProtocolParameter.sol
packages/perennial/test/unit/market/Market.test.ts
packages/perennial/test/unit/marketfactory/MarketFactory.test.ts
packages/perennial/test/unit/types/ProtocolParameter.test.ts

Limits the following parameters to `100%`
- `Intent.fee` field that is passed in in an intent order
- `Protocol.referralFee` global referral fee setting
- `MarketFactory.referralFees` per-referrer referral fee setting

Add interface / solver fee limits

---

package.json
packages/perennial/contracts/Market.sol
packages/perennial/contracts/types/Global.sol
packages/perennial/contracts/types/RiskParameter.sol
yarn.lock

Ensures that the latest -> new storage accessors properly work in `updateRiskParameter` during the v2.3 migration process.
- Cleans up the `updateRiskParameter` logic, to require minimal backwards compatibility.
- Updates `RiskParameter` layout to ensure `takerFee.adiabatic / takerFee.scale` are backwards compatible.

[Fix] riskParameter migration compatibility

---

packages/perennial-extensions/test/integration/core/Orders.test.ts
packages/perennial/contracts/Market.sol
packages/perennial/contracts/interfaces/IMarket.sol
packages/perennial/contracts/types/Guarantee.sol
packages/perennial/test/integration/core/fees.test.ts
packages/perennial/test/integration/core/happyPath.test.ts
packages/perennial/test/integration/core/liquidate.test.ts
packages/perennial/test/unit/market/Market.test.ts
patches/@nomicfoundation+hardhat-chai-matchers+1.0.6.patch
yarn.lock

- Adds `liquidator`, `orderReferrer`, and `guaranteeReferrer` to the `OrderCreated` event.
- Incorporates https://github.com/equilibria-xyz/perennial-v2/pull/359 into v2.3.
- Adds extra logic to `hardhat-chai-matchers` to output all eligible events in the event that a `.to.emit().withArgs()` fails.

Add address metadata to OrderCreated event

---

packages/perennial-extensions/test/integration/core/Pyth.test.ts
packages/perennial-oracle/contracts/Oracle.sol
packages/perennial-oracle/contracts/keeper/KeeperOracle.sol
packages/perennial-oracle/test/integration/metaquants/MetaQuantsOracleFactory.test.ts
packages/perennial-oracle/test/integration/pyth/PythOracleFactory.test.ts
packages/perennial-oracle/test/integrationSepolia/chainlink/ChainlinkOracleFactory.test.ts
packages/perennial-oracle/test/unit/chainlink/ChainlinkFactory.test.ts
packages/perennial-oracle/test/unit/oracle/KeeperOracle.test.ts
packages/perennial-oracle/test/unit/oracle/Oracle.test.ts
packages/perennial-oracle/test/unit/pyth/PythOracleFactory.test.ts
packages/perennial/contracts/Market.sol
packages/perennial/contracts/interfaces/IOracleProvider.sol

Adds a `newPrice` boolean argument to the `oracleProvider.request()` function which allows the end consumer to specify whether they would like a fresh price at the current timestamp, or whether it is acceptable to carry forward the latest previous price.
In either case a price is guaranteed to be populated at the current version in order as expected, however requests that do not require a fresh price do not need to pay for the settlement fee they do not trigger a keeper callback directly.
This allows us to remove all price-override logic from the market because we can ensure that a price is available for any case of market update.

Add newPrice option oracle request

---

package.json
packages/perennial-account/contracts/Account.sol
packages/perennial-account/contracts/Controller.sol
packages/perennial-account/contracts/Controller_Arbitrum.sol
packages/perennial-account/contracts/interfaces/IAccount.sol
packages/perennial-account/contracts/interfaces/IController.sol
packages/perennial-account/test/helpers/arbitrumHelpers.ts
packages/perennial-account/test/helpers/setupHelpers.ts
packages/perennial-account/test/integration/Controller_Arbitrum.ts
packages/perennial-account/test/unit/Controller.ts
yarn.lock

https://github.com/equilibria-xyz/root/pull/97 adds _create2_ functionality to the existing `Factory` attribute, and is a dependency for this change.  Will need to update `package.json` once a new RC is published, such that everything (including CI) will compile and run.  Until then, can use `yarn link` to use a local checkout of that `root` branch.
This PR deterministically deploys _Accounts_ to a `BeaconProxy`, similar to how factories are used elsewhere in the protocol.  The proxy for the _Controller_ itself is to be handled as a deployment task, outside the scope of this PR.

Collateral accounts: deploy accounts to a BeaconProxy

---

packages/perennial-oracle/contracts/keeper/KeeperOracle.sol

Emits the `OracleVersionFulfilled` before making the settlement callback in the KeeperOracle for better cleanliness with respect to the data pipeline.

Flip OracleVersionFulfilled / settlement callback order

---

packages/common/testutil/types.ts
packages/perennial/contracts/Market.sol
packages/perennial/contracts/libs/InvariantLib.sol
packages/perennial/contracts/libs/VersionLib.sol
packages/perennial/contracts/types/Global.sol
packages/perennial/test/integration/core/fees.test.ts
packages/perennial/test/integration/core/happyPath.test.ts
packages/perennial/test/integration/helpers/setupHelpers.ts
packages/perennial/test/unit/market/Market.test.ts
packages/perennial/test/unit/types/Global.test.ts

- Removes `latestPrice` from `Global` in favor of directly using oracle price now that [all prices are available](https://github.com/equilibria-xyz/perennial-v2/pull/363).
- Removes a significant amount of special-casing in the invariant that supported settling via "no-op updates".
- `MarketInvalidProtectionError`
- Require collateral change to be zero (could previously deposit, simplifies maintenance check)
- Allow order position change of zero (removes the need for an additional position check on top of the "closes all" check)
- `MarketStalePriceError`
- Require for all updates (removes exception for zero position accounts and deposits)
- `MarketProtectedError`
- Require for all updates (removes exception for order position change of zero)
- `MarketInsufficientCollateralError`
- Require …

Remove no-op updates

---

packages/perennial-oracle/contracts/types/OracleParameter.sol
packages/perennial-oracle/test/unit/types/OracleParameter.ts
packages/perennial/contracts/types/Global.sol
packages/perennial/test/integration/core/fees.test.ts
packages/perennial/test/unit/market/Market.test.ts
packages/perennial/test/unit/types/Global.test.ts
packages/perennial/test/unit/types/Version.test.ts

Previously, the oracle and risk fees were taken out of the market fee in parallel and therefore needed to total less than 100%.
Since oracle fee is now defined in the oracle layer, we want to decouple these. The PR changes the fee order to:
1. Take protocol fee out of market fee
2. Take oracle fee out of leftover market fee
3. Take risk fee out of leftover market fee
4. Remaining market fee is donation

Make oracle and risk fees independent

---

packages/perennial/contracts/libs/InvariantLib.sol
packages/perennial/test/unit/market/Market.test.ts

Re-adds UX-based exceptions to the stale price check in the invairant:
- No longer need a fresh price for deposits
- No longer need a fresh price for withdrawals when there is no position in the account

Re-add staleAfter exceptions

---

packages/common/testutil/types.ts
packages/perennial-oracle/contracts/Oracle.sol
packages/perennial-oracle/contracts/interfaces/IKeeperOracle.sol
packages/perennial-oracle/contracts/keeper/KeeperOracle.sol
packages/perennial-oracle/test/integration/pyth/PythOracleFactory.test.ts
packages/perennial-oracle/test/unit/chainlink/ChainlinkFactory.test.ts
packages/perennial-oracle/test/unit/oracle/KeeperOracle.test.ts
packages/perennial-oracle/test/unit/oracle/Oracle.test.ts
packages/perennial-oracle/test/unit/pyth/PythOracleFactory.test.ts
packages/perennial/contracts/Market.sol
packages/perennial/contracts/interfaces/IOracleProvider.sol
packages/perennial/contracts/libs/VersionLib.sol
packages/perennial/contracts/types/Global.sol
packages/perennial/test/integration/core/fees.test.ts
packages/perennial/test/integration/core/happyPath.test.ts
packages/perennial/test/unit/market/Market.test.ts
packages/perennial/test/unit/types/Global.test.ts
packages/perennial/test/unit/types/Version.test.ts

There doesn't seem to be a good way to consolidate both no-new-version requests with unrequested versions without causing ordering conflicts when prices are later committed.
For now we'll remove the `newPrice` flag and re-add the `latestPrice` field to `Global`.

Remove newPrice request option

---

packages/perennial/contracts/Market.sol
packages/perennial/test/unit/market/Market.test.ts

During settle-only mode, new prices can still be committed un-requested causing a new version to cut via the sync-phase.
This makes it very hard to ensure all local accounts are synced up to the latest global during an async migration.
- When in settle-only mode, `settle()` will only run the settlement phase, and will skip the sync phase.
While this makes migrations significantly safer, we still require the `makerValue`/`longValue`/`shortValue` to be continually backwards compatible in `Version`.

Only settle in settle-only mode

---

packages/common/testutil/time.ts
packages/perennial-extensions/contracts/Coordinator.sol
packages/perennial-extensions/test/unit/Coordinator/Coordinator.test.ts
packages/perennial-oracle/contracts/Oracle.sol
packages/perennial-vault/test/integration/vault/Vault.test.ts
packages/perennial/contracts/Market.sol
packages/perennial/contracts/interfaces/IMarket.sol
packages/perennial/test/integration/core/fees.test.ts
packages/perennial/test/integration/core/liquidate.test.ts
packages/perennial/test/unit/market/Market.test.ts

- add `account` parameter to `IMarket.claimFee`
- introduce `onlyOperator` modifier
- update `FeeClaimed` event to show both who earned the fee and who claimed it

Add support for operator on claimFee

---

packages/perennial-extensions/contracts/MultiInvoker.sol
packages/perennial-extensions/contracts/interfaces/IMultiInvoker.sol
packages/perennial-extensions/test/helpers/invoke.ts
packages/perennial-extensions/test/integration/core/Invoke.test.ts
packages/perennial-extensions/test/integration/helpers/setupHelpers.ts
packages/perennial-verifier/test/helpers/erc712.ts
packages/perennial/contracts/Market.sol
packages/perennial/contracts/interfaces/IMarket.sol
packages/perennial/test/unit/market/Market.test.ts

Adds an `account` parameter to the intent `update()` signifying to the maker in the match. This allows intent orders to be filled by an operator is one is approved for account.

Add operator to intent update

---

packages/perennial/contracts/Market.sol
packages/perennial/contracts/MarketFactory.sol
packages/perennial/contracts/interfaces/IMarket.sol

Refactors last used field (`referralFee`) of `ProtocolParameter` to return as part of the `authorization` logic instead, which allows us to remove its loading altogether in the `Context`.
Saves `256 bytes` code size.

[Code Size] Remove protocol parameter from context

---

packages/perennial/contracts/Market.sol
packages/perennial/contracts/interfaces/IMarket.sol
packages/perennial/contracts/libs/CheckpointLib.sol
packages/perennial/contracts/libs/VersionLib.sol
packages/perennial/contracts/test/CheckpointTester.sol
packages/perennial/test/unit/types/Checkpoint.test.ts
packages/perennial/test/unit/types/Version.test.ts

Moves the calls to emit `PositionProcessed` and `AccountPositionProcessed` into `VersionLib` and `CheckpointLib` respectively prior to returning the accumulation result.
We leave a copy of the events in `IMarket` for offchain interface compatibility.
This saves `479 bytes` of code size.

[Code Size] Move position processed events into respective libraries

---

packages/perennial-extensions/contracts/MultiInvoker.sol
packages/perennial-extensions/contracts/interfaces/IMultiInvoker.sol
packages/perennial-extensions/test/helpers/invoke.ts
packages/perennial-extensions/test/integration/core/Invoke.test.ts
packages/perennial-extensions/test/unit/MultiInvoker/MultiInvoker.test.ts

Adds a _MultiInvoker_ action which claims earned market fees for the user and automatically unwraps to USDC.

Add CLAIM_FEE action to MultiInvoker

---

packages/perennial/contracts/Market.sol
packages/perennial/contracts/libs/CheckpointLib.sol
packages/perennial/contracts/libs/VersionLib.sol
packages/perennial/contracts/test/CheckpointTester.sol
packages/perennial/contracts/test/GlobalTester.sol
packages/perennial/contracts/test/LocalTester.sol
packages/perennial/contracts/test/VersionTester.sol
packages/perennial/contracts/types/Global.sol
packages/perennial/contracts/types/Local.sol
packages/perennial/test/integration/core/fees.test.ts
packages/perennial/test/unit/types/Checkpoint.test.ts
packages/perennial/test/unit/types/Global.test.ts
packages/perennial/test/unit/types/Local.test.ts
packages/perennial/test/unit/types/Version.test.ts

Now that we are [emitting the position processed events](https://github.com/equilibria-xyz/perennial-v2/pull/407) inside of their respective libraries, we no longer need to return the bulk of the accumulation response data back to Market.
This PR two new paired down response structs for the Checkpoint and Version libs respectively, significantly cutting down on code size.
- Also fixes a bug where VersionLib was early-returning, not emitting its event.
Save `679 bytes` code size.

[Code Size] Return only necessary fields from CheckpointLib / VersionLib

---

packages/perennial/contracts/Market.sol
packages/perennial/contracts/interfaces/IMarket.sol
packages/perennial/contracts/types/Order.sol
packages/perennial/test/unit/market/Market.test.ts

Adds a new overload for `update` which takes a (simplified) order definition directly instead of creating an order based on the difference between the account's current and requested absolute positions.

Add position delta overload for update

---

packages/perennial/contracts/Market.sol
packages/perennial/contracts/interfaces/IMarket.sol
packages/perennial/contracts/types/Position.sol
packages/perennial/test/unit/market/Market.test.ts

Adds migration flow to consolidate the global and local Position storage layouts from 2 to 1 slots (due to refactoring in v2.2).
- The global Position exposes a `migrate()` function that must be called atomically (for each market) upon implementation upgrade. This bypasses the need for a layout version flag.
- The local Position will upgrade async, so we must track this with a new `layout` field in storage.
- A value of `0` denotes either an old-layout `Position` or an unset Position. In both cases, the storage library will read from the v2.2 storage location. This is intended behavior in the former case, and safe in the latter case (due to the second slot still being reserved, and unset).
- A value of `1` denotes that the Position has been successfully updated in state.
- Once all …

Add Position storage migration

---

packages/perennial-deploy/tasks/multisig_ops/buildCreateMarket.ts

Quick one to update the hardhat task which builds a multisig payload to launch a new market. When launching multiple markets at once, we need to add the ability to specify a nonce offset when determining the resulting addresses from the factory creation methods

add nonce offset support to market creation task

---

packages/perennial-account/contracts/libs/RebalanceLib.sol
packages/perennial-account/test/helpers/arbitrumHelpers.ts
packages/perennial-account/test/helpers/setupHelpers.ts
packages/perennial-account/test/integration/Controller_Arbitrum.ts

Contract size with default optimizer runs went from 20.749 to 20.995; no concerns.

Collateral Accounts - Made RebalanceLib library internal

---

packages/perennial-account/contracts/Controller.sol
packages/perennial-account/contracts/Controller_Arbitrum.sol
packages/perennial-account/contracts/Controller_Incentivized.sol
packages/perennial-account/test/helpers/arbitrumHelpers.ts
packages/perennial-account/test/integration/Controller_Arbitrum.ts
packages/perennial-order/contracts/Manager.sol

Issue: https://linear.app/perennial/issue/PE-1789/remove-public-states-set-in-constructor-from-upgradeable-contracts

Fix public immutable state

---

packages/perennial/contracts/types/MarketParameter.sol
packages/perennial/test/integration/core/happyPath.test.ts
packages/perennial/test/integration/helpers/setupHelpers.ts

Fixes https://github.com/sherlock-audit/2024-08-perennial-v2-update-3-judging/issues/90
Also removed non-existant parameters from unit tests.

Fix issue with MarketParameter storage layout

---

packages/perennial-account/contracts/Controller_Arbitrum.sol
packages/perennial-account/contracts/Controller_Incentivized.sol
packages/perennial-account/test/helpers/arbitrumHelpers.ts
packages/perennial-account/test/integration/Controller_Arbitrum.ts
packages/perennial-order/contracts/Manager.sol
packages/perennial-order/test/integration/Manager_Arbitrum.test.ts
packages/perennial-order/test/unit/Manager.test.ts

Fixes https://github.com/sherlock-audit/2024-08-perennial-v2-update-3-judging/issues/92

Fix issue with keeper compensation

---

packages/perennial-oracle/contracts/keeper/KeeperOracle.sol
packages/perennial-oracle/contracts/keeper/KeeperOracle_Migration.sol

Adds a Noop v2.3 migration shim for the `KeeperOracle`.
1. Enter settle-only mode
2. Settle up all accounts in the system
3. Deploy new v2.3 KeeperOracle
4. Commit fresh price more recent than the previous latest (important that this happens prior to the next step)
5. Update the Oracle to the new KeeperOracle
6. Upgrade the prior KeeperOracle to the shim implementation
Market should now be able to update.
- After (2) all accounts will be settled up to the same version `v` (either a requested or unrequested version) along with global.
- (4) will only work because of this [try/catch](https://github.com/equilibria-xyz/perennial-v2_private/pull/15/files#diff-a24c8ce062ad04684b31e345eee9b359bf296aac024925fa40df4ceb88576272R147) that has been added. Previously, all posted prices require the …

[Fix] Add KeeperOracle migration shim

---

packages/perennial/contracts/libs/CheckpointLib.sol
packages/perennial/contracts/libs/InvariantLib.sol
packages/perennial/contracts/test/GuaranteeTester.sol
packages/perennial/contracts/types/Guarantee.sol
packages/perennial/test/unit/market/Market.test.ts
packages/perennial/test/unit/types/Guarantee.test.ts

Fixes https://github.com/sherlock-audit/2024-08-perennial-v2-update-3-judging/issues/42
Includes the expected collateral adjustment based on the difference between the latest oracle price and the price override if present when calculating the margin requirement in the invariant.

Fix margin check to incorporate price override

---

packages/perennial/contracts/types/RiskParameter.sol
packages/perennial/test/unit/types/RiskParameter.test.ts

Fixes https://github.com/sherlock-audit/2024-08-perennial-v2-update-3-judging/issues/41

Fix validation issue caused by truncation of risk params

---

packages/perennial-extensions/contracts/MultiInvoker.sol
packages/perennial-extensions/test/unit/MultiInvoker/MultiInvoker.test.ts

Seems this test broke smock's `returnsAtCall` facility.  Resetting between claim calls fixed it.

Resolve extension test failure

---

packages/common/testutil/types.ts
packages/perennial-account/test/helpers/setupHelpers.ts
packages/perennial-extensions/test/integration/helpers/setupHelpers.ts
packages/perennial-oracle/test/integration/metaquants/MetaQuantsOracleFactory.test.ts
packages/perennial-oracle/test/integration/pyth/PythOracleFactory.test.ts
packages/perennial-oracle/test/integrationSepolia/chainlink/ChainlinkOracleFactory.test.ts
packages/perennial-order/test/helpers/marketHelpers.ts
packages/perennial-vault/test/integration/helpers/setupHelpers.ts
packages/perennial/contracts/interfaces/IMarket.sol
packages/perennial/contracts/libs/InvariantLib.sol
packages/perennial/contracts/test/GuaranteeTester.sol
packages/perennial/contracts/types/Guarantee.sol
packages/perennial/contracts/types/MarketParameter.sol
packages/perennial/test/integration/core/happyPath.test.ts
packages/perennial/test/integration/helpers/setupHelpers.ts
packages/perennial/test/unit/market/Market.test.ts
packages/perennial/test/unit/types/Global.test.ts
packages/perennial/test/unit/types/Guarantee.test.ts
packages/perennial/test/unit/types/MarketParameter.test.ts

Adds a new market parameter: `maxPriceDeviation` which caps the geometric distance that the quoted intent price can be from the underlying oracle price.
Suggested change from: https://github.com/sherlock-audit/2024-08-perennial-v2-update-3-judging/issues/42.

[Fix] Add maximum for intent price deviation

---

packages/perennial-verifier/contracts/Verifier.sol
packages/perennial-verifier/contracts/interfaces/IMarketFactorySigners.sol
packages/perennial-verifier/test/unit/Verifier/Verifier.test.ts

Re-attempt from #472 - Having the multiple market factories was causing some issues in the perennial-deploy package's tasks and tests.

Rename Verifier's market factory interface

---

packages/perennial-order/test/unit/Manager.test.ts

Added a unit test demonstrating that one cannot overwrite a non-spent order with an empty one.

Added unit test for replacement with an empty order

---

packages/perennial-oracle/contracts/chainlink/ChainlinkFactory.sol
packages/perennial-oracle/contracts/interfaces/IKeeperFactory.sol
packages/perennial-oracle/contracts/metaquants/MetaQuantsFactory.sol
packages/perennial-oracle/contracts/pyth/PythFactory.sol
packages/perennial-oracle/test/integration/metaquants/MetaQuantsOracleFactory.test.ts
packages/perennial-oracle/test/unit/chainlink/ChainlinkFactory.test.ts
packages/perennial-oracle/test/unit/pyth/PythOracleFactory.test.ts

Adds a `factoryType` to the `IKeeperFactory` and each implementation. This will make it easier for off-chain systems to know where to pull prices from by mapping the `factoryType` to the off-chain source.
For the `MetaQuantsFactory` the type is dynamically set in the constructor as this factory can be used for different signed price providers. As a followup task, I think we should rename the contract to something like `SignedPriceFactory`

Add string 'factoryType' to IKeeperFactory and impls

---

.gitignore
README.md
package.json
packages/common/hardhat.default.config.ts
packages/core/package.json
packages/oracle/package.json
packages/periphery/package.json
packages/vault/package.json
yarn.lock

After investigating several solutions, decided upon [solidity-docgen](https://github.com/OpenZeppelin/solidity-docgen), on OpenZeppelin project.  Other solutions were evaluated, but had bugs/limitations undesirable to us.
Not building docs into any CI tasks, but can add that if desired.
Also updated README to correct package names and instruct how to generate docs.  Expecting links to fall into place once 2.4 packages are published.

Create script for generating code documentation

---

packages/periphery/contracts/CollateralAccounts/Account.sol
packages/periphery/test/integration/CollateralAccounts/Account.test.ts
packages/periphery/test/integration/CollateralAccounts/Controller_Incentivized.test.ts

This seems more favorable than modifying than modifying `Controller_Incentivized`, as the function is now doing what is implied.  If user wants to _wrap a specific amount_, they may call `wrap`.  If they want to _ensure some amount is wrapped_, they may call `wrapIfNecessary`.

adjust wrapIfNecessary logic

---

packages/periphery/contracts/MultiInvoker/MultiInvoker.sol
packages/periphery/contracts/MultiInvoker/interfaces/IMultiInvoker.sol
packages/periphery/test/integration/MultiInvoker/Invoke.test.ts
packages/periphery/test/integration/MultiInvoker/setupHelpers.ts
packages/vault/contracts/Vault.sol
packages/vault/contracts/VaultFactory.sol
packages/vault/contracts/interfaces/IVaultFactory.sol
packages/vault/test/integration/vault/Vault.test.ts

Issue: https://linear.app/perennial/issue/PE-1979/[cleanup]-consolidate-operator-settings-to-only-marketfactory
Migration Note:
- Ensure that multiInvoker and vault users are notified to approve marketFactory for authorization.
- Update frontend to approve marketFactory for all multiInvoker and vault transactions.

Consolidate operator settings to only marketFactory

---

packages/core/contracts/MarketFactory.sol
packages/core/contracts/types/ProtocolParameter.sol
packages/core/contracts/types/RiskParameter.sol
packages/core/test/integration/helpers/setupHelpers.ts
packages/core/test/unit/market/Market.test.ts
packages/core/test/unit/marketfactory/MarketFactory.test.ts
packages/core/test/unit/types/MarketParameter.test.ts
packages/core/test/unit/types/ProtocolParameter.test.ts
packages/core/test/unit/types/RiskParameter.test.ts
packages/deploy/util/constants.ts
packages/oracle/test/integration/metaquants/MetaQuantsOracleFactory.test.ts
packages/oracle/test/integration/pyth/PythOracleFactory.test.ts
packages/oracle/test/integrationSepolia/chainlink/ChainlinkOracleFactory.test.ts
packages/periphery/test/helpers/setupHelpers.ts
packages/periphery/test/integration/MultiInvoker/setupHelpers.ts

Issue: https://linear.app/perennial/issue/PE-1840/[fix]-since-liq-fee-is-no-longer-checked-against-minmargin-there-is-a
- Deprecated previous protocol parameter slot in marketFactory.
- Add new protocol parameter storage with 2 slots.
Updated protocol parameter slots:
```
// struct StoredProtocolParameter {
//     /* slot 0 (28) */
//     uint24 maxFee;                  // <= 1677%
//     uint32 maxLiquidationFee;       // <= 4294
//     uint24 maxCut;                  // <= 1677%
//     uint32 maxRate;                 // <= 214748% (capped at 31 bits to accommodate int32 rates)
//     uint24 minMaintenance;          // <= 1677%
//     uint24 minEfficiency;           // <= 1677%
//     uint24 referralFee;             // <= 1677%
//     uint24 minScale;                // <= 1677%
// …
```

Add `minMinMaintenance` protocol parameter 

---

packages/perennial-account/contracts/Controller_Optimism.sol
packages/perennial-order/contracts/Manager_Optimism.sol

Copypasta-ed the contracts from v2.4, where they have been tested against a Base fork, and updated imports for naming.   No other changes.  If backmerging into v2.4, the commit within should be ignored.

Optimism contracts for Collateral Account controller and Trigger Order manager

---

packages/periphery/test/helpers/MultiInvoker/invoke.ts
packages/periphery/test/integration/MultiInvoker/Arbitrum.test.ts
packages/periphery/test/unit/MultiInvoker/MultiInvoker.test.ts

Some tests were removed in PR #498 but were relevant to the current code.

Restore multiInvoker tests

---

packages/core/contracts/Market.sol
packages/core/contracts/Verifier.sol
packages/core/contracts/interfaces/IMarket.sol
packages/core/contracts/interfaces/IVerifier.sol
packages/core/contracts/types/MarketUpdateTaker.sol
packages/core/contracts/types/Order.sol
packages/core/contracts/types/Take.sol
packages/core/test/helpers/erc712.ts
packages/core/test/integration/core/happyPath.test.ts
packages/core/test/unit/market/Market.test.ts
packages/core/test/unit/verifier/Verifier.test.ts

Establishes a foundation by which users may change their position through a signed message without using an intent order.  The message implemented in this PR limits users to changing their taker position without collateral change.
Explicitly out-of-scope for this PR is relaying of this message.

Market taker update through signed message

---

.github/workflows/CI.yml
packages/core/contracts/libs/InvariantLib.sol
packages/core/contracts/libs/MagicValueLib.sol
packages/core/contracts/test/OrderTester.sol
packages/core/contracts/types/Order.sol
packages/core/test/integration/core/liquidate.test.ts
packages/core/test/unit/market/Market.test.ts
packages/core/test/unit/types/Order.test.ts

Relaxes the invariant to allow taker orders to cross zero when there are no local pending amm orders (`.invalidation == 0`).
**Note**: This PR does not enable us to place zero-cross orders yet, so testing is limited to not violating any current specification with existing non-zero-cross flows. The final PR in this series will enable zero-cross orders and contain additional test cases for these.
- Must settle up all outstanding local orders

Relax singled sided invariant

---

packages/core/contracts/Market.sol
packages/core/contracts/Verifier.sol
packages/core/contracts/interfaces/IVerifier.sol
packages/core/contracts/types/Fill.sol
packages/core/test/helpers/erc712.ts
packages/core/test/integration/core/happyPath.test.ts
packages/core/test/unit/market/Market.test.ts
packages/core/test/unit/verifier/Verifier.test.ts

In the current implementation, a trader submits the signed intent offchain, and the counterparty "solver" calls an update method to fill the intent.  This change adds a message signed by the solver and submitted to a keeper.  The keeper calls a new update method which fill the trader's intent using both the signature from the trader and solver.

Fill intent order via signed message

---

packages/common/testutil/types.ts
packages/periphery/contracts/CollateralAccounts/AccountVerifier.sol
packages/periphery/contracts/CollateralAccounts/Controller_Incentivized.sol
packages/periphery/contracts/CollateralAccounts/interfaces/IRelayVerifier.sol
packages/periphery/contracts/CollateralAccounts/interfaces/IRelayer.sol
packages/periphery/contracts/CollateralAccounts/types/RelayedTake.sol
packages/periphery/test/helpers/CollateralAccounts/eip712.ts
packages/periphery/test/integration/l2/CollateralAccounts/Arbitrum.test.ts
packages/periphery/test/integration/l2/CollateralAccounts/Controller_Incentivized.test.ts
packages/periphery/test/unit/CollateralAccounts/Controller_Incentivized.test.ts
packages/periphery/test/unit/CollateralAccounts/Verifier.test.ts

This PR extends Collateral Accounts incentivized controller to relay a delta take update to the market specified in the inner `Take` message's _domain_ field.  Note that, per requirements, the keeper submitting the transaction is compensated from the collateral account for which the (inner) market update occurs, not from the signer of the outer `RelayedTake` message.  Other relayed messages pay the keeper from the collateral account of the (outer) wrapped message.

Relayer support for delta update with signature

---

packages/periphery/README.md
packages/periphery/contracts/CollateralAccounts/Controller.sol
packages/periphery/contracts/CollateralAccounts/interfaces/IController.sol
packages/periphery/contracts/TriggerOrders/Manager.sol
packages/periphery/contracts/TriggerOrders/Manager_Arbitrum.sol
packages/periphery/contracts/TriggerOrders/Manager_Optimism.sol
packages/periphery/contracts/TriggerOrders/interfaces/IManager.sol
packages/periphery/test/integration/l2/TriggerOrders/Manager.test.ts
packages/periphery/test/integration/l2/TriggerOrders/Manager_Arbitrum.test.ts
packages/periphery/test/integration/l2/TriggerOrders/Manager_Optimism.test.ts
packages/periphery/test/integration/l2/TriggerOrders/setupTypes.ts
packages/periphery/test/unit/CollateralAccounts/Controller.test.ts
packages/periphery/test/unit/TriggerOrders/Manager.test.ts

To reduce price commitments, have _Manager_ contract use collateral accounts for compensating keepers and paying interface fees.  Since `IAccount.withdraw` cannot be used for this purposes, `IController` has been extended with a `chargeFee` method only callable from an operator.  This facility also wraps USDC if necessary.  Since trigger order `Manager` already needs to be a manager to interact with markets on behalf of the user, no new entitlements are required.  
Trigger order users must create and fund their collateral account prior to using the new version.

Trigger Orders Manager contract to compensate keepers and pay interface fees from collateral accounts rather than market

---

.github/workflows/CI.yml
packages/periphery/test/unit/TriggerOrders/Verifier.test.ts
packages/vault/test/integration/vault/MakerVault.test.ts

Note the issue was caused by test setup; when all `MakerVault` tests were skipped (except one, either `#initialize` or `#name`), the failure still occurred.  Workaround:
- reset the fork after MakerVault tests
- (unrelated) tweak message expiry for when CI is running slow

attempt to resolve integration test issue with SolverVault tests

---

packages/vault/contracts/MakerVault.sol
packages/vault/contracts/SolverVault.sol
packages/vault/contracts/Vault.sol
packages/vault/contracts/interfaces/IMakerVault.sol
packages/vault/contracts/interfaces/ISolverVault.sol
packages/vault/contracts/interfaces/IVault.sol
packages/vault/contracts/libs/MakerStrategyLib.sol
packages/vault/test/integration/vault/MakerVault.test.ts
packages/vault/test/integration/vault/SolverVault.test.ts

Adds a rebalance function to the SolverVault which allows the `coordinator` to move collateral from one registered market to another.

Add rebalance to SolverVault

---

packages/core/contracts/libs/MagicValueLib.sol
packages/core/contracts/types/Guarantee.sol
packages/core/contracts/types/Order.sol
packages/core/test/integration/helpers/setupHelpers.ts
packages/core/test/unit/market/Market.test.ts
packages/core/test/unit/marketfactory/MarketFactory.test.ts
packages/core/test/unit/types/Guarantee.test.ts
packages/core/test/unit/types/Order.test.ts
packages/oracle/test/integration/metaquants/MetaQuantsOracleFactory.test.ts
packages/oracle/test/integration/pyth/PythOracleFactory.test.ts
packages/oracle/test/integrationSepolia/chainlink/ChainlinkOracleFactory.test.ts
packages/periphery/test/helpers/marketHelpers.ts
packages/periphery/test/helpers/setupHelpers.ts

- Makes external
- `LocalOrderLib.store()`
- `GlobalOrderLib.store()`
- Logic cleanup
- `Order.from()`
- Makes external
- `LocalGuaranteeLib.store()`
- `GlobalGuaranteeLib.store()`
- Makes internal
- `MagicValueLib.process()`
- Removes redundant clause [here](https://github.com/equilibria-xyz/perennial-v2/pull/550/files#diff-0a101158e345c3ee4438c191c98ab25025e9421ad80c9a6549fb9af660ea34b2L57).
- If zero-cross, a zero currentPosition is returned
- else .min(currentPosition) returns a zero currentPosition
Saves 948 bytes.

[Code Size] v2.4 mini

---

.github/workflows/CI.yml
packages/periphery/contracts/CollateralAccounts/Account.sol
packages/periphery/contracts/CollateralAccounts/interfaces/IAccount.sol
packages/periphery/test/integration/l2/CollateralAccounts/Account.test.ts
packages/periphery/test/integration/l2/CollateralAccounts/Arbitrum.test.ts
packages/periphery/test/unit/CollateralAccounts/Controller.test.ts
packages/periphery/test/unit/TriggerOrders/Verifier.test.ts

`withdraw` now treats `amount` parameter as a maximum rather than absolute - This is cleaner than adding several calculations in the case where `shouldUnwrap == true`.

Collateral Account - handle redeemPrice < 1 when unwrapping

---

.github/workflows/CI.yml
packages/core/contracts/libs/InvariantLib.sol
packages/core/contracts/libs/VersionLib.sol
packages/core/contracts/types/Order.sol
packages/core/test/unit/market/Market.test.ts

Approximates the outstanding intent trade fees by measuring all outstanding trade fees.
Applies these to:
- margin check
- maintenance check
- collateral below zero check
Resolves: https://audits.sherlock.xyz/contests/764/voting/31.

[Audit Fix] Take intent fees into account in invariant

---

packages/vault/contracts/Vault.sol
packages/vault/test/integration/vault/MakerVault.test.ts
packages/vault/test/integration/vault/SolverVault.test.ts

Code for awarding profit shares assumes _account_ and _coordinator_ are two separate actors.  But if account == coordinator, the `_credit` call has no effect because shares are later overwritten when context is stored.  To resolve this, pass account being settled into `_credit` and update context if receiver account is same account being settled.

Prevent overwriting coordinator shares when settling

---

packages/core/contracts/Market.sol
packages/core/contracts/interfaces/IMarket.sol
packages/core/test/integration/core/happyPath.test.ts
packages/core/test/integration/helpers/setupHelpers.ts
packages/core/test/unit/market/Market.test.ts

- Removes unused beneficiary code.
- Removes public `coordinator` getter.

[Code Size] Remove coordinator / beneficiary getters

---

packages/core/contracts/Market.sol
packages/core/contracts/test/GuaranteeTester.sol
packages/core/contracts/test/OrderTester.sol
packages/core/contracts/types/Guarantee.sol
packages/core/contracts/types/Order.sol
packages/core/test/unit/types/Guarantee.test.ts
packages/core/test/unit/types/Order.test.ts

Removes `.next()` methods on `Order` and `Guarantee` in favor of `.fresh()` methods which instantiate new copies of these objects instead.
This causes a very slight gas increase w/ a considerable reduction in code siz: `120 bytes`.

[Code Size] Clean up .next() methods

---

packages/core/contracts/Market.sol
packages/oracle/contracts/OracleFactory.sol
packages/periphery/contracts/MultiInvoker/types/TriggerOrder.sol
packages/vault/contracts/Vault.sol

`v2.4-mini` no longer needs to be backwards compatible with `v2.3` for this deployment.
As such we can remove these deprecated slots, which would have otherwise changes the storage layout of the already deployed contracts.
related to: https://github.com/equilibria-xyz/perennial-v2/pull/568.

[Code Size] Remove unused storage slots

---

.github/workflows/CI.yml
packages/periphery/test/integration/TriggerOrders/Arbitrum.test.ts

When mocha tests are run with retries enabled, errors raised in `afterEach` clauses are suppressed.  This leads to misleading error messages.  In particular, when `periphery` integration tests fail due to gas configuration, CI omits the gas out-of-range error, and shows only subsequent errors for nonce/orderId mismatch.
Since retries are not useful for periphery integration tests, disable them in CI.

Disable retries in periphery integration test CI

---

packages/core/contracts/Market.sol
packages/core/test/integration/core/closedProduct.test.ts
packages/core/test/integration/core/fees.test.ts
packages/core/test/integration/core/happyPath.test.ts
packages/core/test/integration/helpers/setupHelpers.ts

- Global settlement invoked by oracle after a price commitment is making lots of seemingly unnecessary `_processOrderLocal` calls.  Found it in my branch, where `Margin` contract was getting calls to write checkpoints for the 0 address.  To optimize for space instead of gas, we could instead have `_processOrderLocal` immediately return if account is 0 address.
- Sidequest: Fixed `multi-delayed update w/ collateral (gas)` integration test, which was not functional.
- Resolved some unrelated linter warnings.

prevent _processOrderLocal call for 0 address

---

packages/core/test/integration/core/happyPath.test.ts

- There was already a test to cover invalid price, but I extended it to ensure a new position settled after commiting a valid price.
- Added a new short position test which checks state on both opening and closing the position.
- Created a test which fakes a stale oracle price, ensuring opening and closing a maker order is rejected when price is stale.

Additional "Happy Path" integration tests
