packages/perennial-extensions/contracts/MultiInvoker.sol
Fixes https://github.com/sherlock-audit/2023-09-perennial-judging/issues/60.
=> [Fix] Adjust current position in MultiInvoker.liquidate()

packages/perennial-extensions/contracts/MultiInvoker.sol
Fixes https://github.com/sherlock-audit/2023-09-perennial-judging/issues/61.
=> [Fix] Adjust current position in MultiInvoker.executeOrder()

packages/perennial-extensions/contracts/MultiInvoker.sol, packages/perennial-extensions/test/integration/core/Liquidate.test.ts
Fixes issue where the latest market price was used for the MultiInvoker liquidation calculation instead of the latest oracle price.
=> [Fix] Incorrect price used in MultiInvoker liquidation calculation

package.json, packages/perennial-extensions/contracts/MultiInvoker.sol, packages/perennial-extensions/test/integration/core/Invoke.test.ts, packages/perennial-oracle/contracts/OracleFactory.sol, packages/perennial-oracle/contracts/pyth/PythFactory.sol, packages/perennial-oracle/contracts/pyth/PythOracle.sol, packages/perennial-oracle/test/integration/pyth/PythOracle.test.ts, packages/perennial-oracle/test/unit/oracle/Oracle.test.ts, packages/perennial-oracle/test/unit/oracle/OracleFactory.test.ts, packages/perennial-payoff/test/unit/PayoffFactory/PayoffFactory.test.ts, packages/perennial-vault/test/integration/vault/Vault.test.ts, packages/perennial/contracts/Market.sol, packages/perennial/test/unit/market/Market.test.ts, packages/perennial/test/unit/marketfactory/MarketFactory.test.ts, yarn.lock
Implements the `root` renaming change [here](https://github.com/equilibria-xyz/root/pull/73).
=> Implement root rename

packages/perennial-extensions/contracts/MultiInvoker.sol, packages/perennial-extensions/contracts/types/TriggerOrder.sol, packages/perennial-extensions/test/helpers/invoke.ts, packages/perennial-extensions/test/helpers/types.ts, packages/perennial-extensions/test/integration/core/Orders.test.ts, packages/perennial-extensions/test/unit/MultiInvoker/MultiInvoker.test.ts, yarn.lock
Add maker option to trigger orders in invoker
=> add maker side to trigger orders

packages/perennial-extensions/contracts/MultiInvoker.sol, packages/perennial-extensions/contracts/types/TriggerOrder.sol, packages/perennial-extensions/test/integration/core/Orders.test.ts
Trigger delta of 0 sets the trigger's position side to 0 instead of adding 0 to the current position
=> Magic "close all" trigger orders

package.json, packages/perennial-extensions/contracts/MultiInvoker.sol, packages/perennial-extensions/contracts/interfaces/IMultiInvoker.sol, packages/perennial-extensions/test/integration/core/Pyth.test.ts, packages/perennial-extensions/test/integration/helpers/setupHelpers.ts, packages/perennial-extensions/test/unit/MultiInvoker/MultiInvoker.test.ts, packages/perennial-oracle/contracts/Oracle.sol, packages/perennial-oracle/contracts/interfaces/IKeeperFactory.sol, packages/perennial-oracle/contracts/interfaces/IOracle.sol, packages/perennial-oracle/contracts/keeper/KeeperFactory.sol, packages/perennial-oracle/contracts/keeper/KeeperOracle.sol, packages/perennial-oracle/contracts/pyth/PythFactory.sol, packages/perennial-oracle/contracts/pyth/PythFactory_Arbitrum.sol, packages/perennial-oracle/contracts/pyth/PythFactory_Optimism.sol, packages/perennial-oracle/test/integration/oracle/OracleFactory.test.ts, packages/perennial-oracle/test/integration/pyth/PythOracle.test.ts, packages/perennial-oracle/test/integration/pyth/PythOracleFactory.test.ts, packages/perennial-oracle/test/unit/oracle/Oracle.test.ts, packages/perennial-oracle/test/unit/pyth/PythOracleFactory.test.ts, yarn.lock
=> Merge root v2.1 - Update Kept modifier, use onlyFactory modifier

packages/perennial-extensions/contracts/MultiInvoker.sol
remove unnecessary IMarket interface cast
=> Remove Interface cast

packages/perennial-extensions/contracts/MultiInvoker.sol, packages/perennial-extensions/contracts/MultiInvoker_Arbitrum.sol, packages/perennial-extensions/test/unit/MultiInvoker/MultiInvoker.test.ts, packages/perennial-extensions/test/unit/MultiInvoker/MultiInvoker_Arbitrum.test.ts
#147 did not fully fix this incentivization issue because the MultiInvoker did not inherent from an L2 specific Kept impl.
=> MultiInvoker_Arbitrum

packages/perennial-oracle/test/unit/oracle/Oracle.test.ts
- Some checks for non-zero -> zero
- zero -> non-zero
- zero -> zero -> zero
=> More tests around updating to/from zero-timestamp oracles

packages/perennial-oracle/contracts/keeper/KeeperFactory.sol, packages/perennial-oracle/test/integration/pyth/PythOracleFactory.test.ts
Resolves: https://github.com/sherlock-audit/2023-10-perennial-judging/issues/50.
=> [Fix] KeeperFactory.settle() empty array constraint

packages/perennial-oracle/contracts/keeper/KeeperOracle.sol, packages/perennial-oracle/hardhat.config.ts, packages/perennial-oracle/test/integration/pyth/PythOracleFactory.test.ts
Resolves https://github.com/sherlock-audit/2023-10-perennial-judging/issues/25.
=> [Fix] Multiple callback registrations during the same version

packages/perennial-extensions/contracts/MultiInvoker.sol, packages/perennial-extensions/contracts/types/TriggerOrder.sol, packages/perennial-extensions/test/unit/MultiInvoker/MultiInvoker.test.ts
Resolves: https://github.com/sherlock-audit/2023-10-perennial-judging/issues/31.
=> [Fix] Order eligibility w/ invalid versions

packages/perennial-vault/contracts/lib/StrategyLib.sol, packages/perennial-vault/test/integration/vault/Vault.test.ts
Resolves: https://github.com/sherlock-audit/2023-10-perennial-judging/issues/28.
=> [Fix] Incorporate fees in strategy calculation

.github/workflows/CI.yml
Reverts equilibria-xyz/perennial-v2#160
=> Revert "Enable manual CI"

package.json, packages/perennial-vault/contracts/Vault.sol, packages/perennial-vault/contracts/lib/StrategyLib.sol, packages/perennial-vault/contracts/types/Checkpoint.sol, packages/perennial/contracts/Market.sol, packages/perennial/contracts/types/Position.sol, yarn.lock
- Saves `~300 bytes` code size in `Vault.sol`
=> Use new unsafeXXX number helpers

package.json, packages/perennial-extensions/contracts/MultiInvoker.sol, packages/perennial-extensions/contracts/MultiInvoker_Arbitrum.sol, packages/perennial-extensions/test/integration/core/Orders.test.ts, packages/perennial-oracle/contracts/keeper/KeeperFactory.sol, packages/perennial-oracle/contracts/pyth/PythFactory.sol, packages/perennial-oracle/contracts/pyth/PythFactory_Arbitrum.sol, packages/perennial-oracle/contracts/pyth/PythFactory_Optimism.sol, packages/perennial-oracle/test/integration/pyth/PythOracleFactory.test.ts, yarn.lock
Incorporate changes from: https://github.com/equilibria-xyz/root/pull/84.
=> [Cleanup] Use new Kept

packages/perennial-vault/contracts/Vault.sol, packages/perennial-vault/contracts/interfaces/IVault.sol, packages/perennial-vault/contracts/lib/StrategyLib.sol, packages/perennial-vault/test/integration/vault/Vault.test.ts
Refactor saves the Vault:
- `1.3kb`
- `59 LoC`
=> [Cleanup] Vault allocation rework

packages/perennial-vault/contracts/Vault.sol, packages/perennial-vault/contracts/interfaces/IVault.sol, packages/perennial-vault/contracts/lib/StrategyLib.sol, packages/perennial-vault/contracts/types/Checkpoint.sol, packages/perennial-vault/test/integration/vault/Vault.test.ts
Adds ability to rebalance collateral without triggering a position update, which allows for claiming to no longer need to charge the settlement fee.
=> Make Vault claim free

packages/perennial-extensions/contracts/MultiInvoker.sol
- Use pre-settlement flow instead of virtually computing the settlement.
=> [Cleanup] MultiInvoker settlement flow

README.md
fixes npm badge for oracle and payoff packages
=> Fix NPM package badge in README 

packages/perennial-vault/contracts/lib/StrategyLib.sol, packages/perennial/contracts/test/PositionTester.sol, packages/perennial/contracts/types/Position.sol, packages/perennial/test/unit/types/Position.test.ts
Removes `net()` and simplifies the logic of `makerSocializedPortion`.
=> [Cleanup] Simplify Position

package.json, packages/perennial/contracts/types/Version.sol, yarn.lock
Incorporates final changes from root addition: https://github.com/equilibria-xyz/root/pull/87.
=> Update Adiabatic Fee

packages/perennial/contracts/Market.sol, packages/perennial/contracts/interfaces/IMarket.sol
Normalizes `load / store` pattern across contexts for
- Full transaction
- Settlement process
- Update Process
=> [Cleanup] Normalize context loading / storing

packages/perennial-vault/contracts/Vault.sol, packages/perennial-vault/test/integration/vault/Vault.test.ts
Fixes issue where the vault incorrectly still was rebalancing position on a claim.
=> [Fix] Don't rebalance on claim

packages/perennial/contracts/Market.sol, packages/perennial/contracts/interfaces/IMarket.sol, packages/perennial/test/unit/market/Market.test.ts
Required for the v2.2 payoff oracle migration
=> Add oracle update function to Market

packages/perennial-extensions/test/integration/core/Orders.test.ts, packages/perennial/contracts/Market.sol, packages/perennial/contracts/interfaces/IMarket.sol, packages/perennial/test/integration/core/fees.test.ts, packages/perennial/test/integration/core/happyPath.test.ts, packages/perennial/test/integration/core/liquidate.test.ts, packages/perennial/test/unit/market/Market.test.ts
- Cleans up local / global order processed events
- Adds referrer to update event
=> [Cleanup] Events

packages/perennial/test/unit/types/Version.test.ts
Feel free to comment with any additional use cases/scenarios for which you would like to see coverage.  Also happy to discuss code/style, verbosity of comments, and such.
=> Add settlementFee / liquidationFee / exposure tests

packages/perennial/test/integration/core/liquidate.test.ts
`minMaintenance` is a fixed-amount risk parameter.   To ensure liquidations are incentivized, user must maintain at least that amount of collateral regardless of the maintenance requirements for their position.  Implemented a unit test which drops a user's collateral under the `minMaintenance` amount and then liquidates the user.
=> Unit test to liquidate user under minMaintenance

packages/perennial/test/integration/core/fees.test.ts
Tests ensure the proper amount of the base fee is claimable by the referrer after account settlement.
=> Integration tests for referral fee

packages/perennial/contracts/Market.sol, packages/perennial/contracts/interfaces/IMarket.sol, packages/perennial/contracts/libs/InvariantLib.sol
=> Collapse Context and UpdateContext structs

.github/workflows/CI.yml
Reverts equilibria-xyz/perennial-v2#178
=> Revert "Revert "Enable manual CI""

packages/perennial/contracts/Market.sol, packages/perennial/test/unit/market/Market.test.ts
Resolves: https://github.com/sherlock-audit/2024-02-perennial-v2-3-judging/issues/16.
=> [v2.2 Audit Fix] Fix claimable credit to local context

packages/perennial-extensions/contracts/MultiInvoker.sol
https://github.com/sherlock-audit/2024-02-perennial-v2-3-judging/issues/28
=> [v2.2 Audit Optimization] Use sendValue instead of transfer to allow for receiving contracts to use more gas

packages/perennial-oracle/contracts/chainlink/ChainlinkFactory.sol, packages/perennial-oracle/test/integrationSepolia/chainlink/ChainlinkOracleFactory.test.ts
https://github.com/sherlock-audit/2024-02-perennial-v2-3-judging/issues/32
=> [v2.2 Audit Fix] Only pay keeper fees for requested versions in ChainlinkFactory

packages/perennial/test/integration/core/fees.test.ts
After researching further, this is not an issue.
=> Remove subtractive fee overclaim TODOs

packages/perennial/contracts/Market.sol, packages/perennial/contracts/MarketFactory.sol, packages/perennial/contracts/interfaces/IMarketFactory.sol, packages/perennial/test/unit/market/Market.test.ts, packages/perennial/test/unit/marketfactory/MarketFactory.test.ts
Adds the ability for a protocol owner to enable a protocol-wide operator.
=> Add protocol operator

packages/perennial-extensions/contracts/MultiInvoker.sol
https://github.com/sherlock-audit/2024-05-kwenta-x-perennial-integration-update-judging/issues/4
=> [Delegate MultiInvoker Audit FIx] Fix natspec for MultiInvoker._deposit

packages/perennial-oracle/test/unit/oracle/KeeperOracle.test.ts
An update introduced in the v2.2 change stale version (thereby invalid) commits to still make the settlement callback to market, where it previously was skipped.
=> [Fix] KeeperOracle test after v2.2 -> v2.3 merge

package.json, packages/perennial-deploy/package.json, packages/perennial-extensions/package.json, packages/perennial-oracle/package.json, packages/perennial-vault/package.json, packages/perennial/package.json
Publishing as `1.2.1` due initial error.
=> Publish v2.2 package

packages/perennial-account/README.md, packages/perennial-account/contracts/Controller.sol, packages/perennial-account/contracts/Controller_Arbitrum.sol, packages/perennial-account/contracts/Verifier.sol, packages/perennial-account/contracts/interfaces/IController.sol, packages/perennial-account/contracts/interfaces/IVerifier.sol, packages/perennial-account/contracts/libs/RebalanceLib.sol, packages/perennial-account/contracts/types/Action.sol, packages/perennial-account/contracts/types/DeployAccount.sol, packages/perennial-account/contracts/types/MarketTransfer.sol, packages/perennial-account/contracts/types/RebalanceConfigChange.sol, packages/perennial-account/contracts/types/SignerUpdate.sol, packages/perennial-account/contracts/types/Withdrawal.sol, packages/perennial-account/test/helpers/arbitrumHelpers.ts, packages/perennial-account/test/helpers/erc712.ts, packages/perennial-account/test/helpers/setupHelpers.ts, packages/perennial-account/test/integration/Controller.ts, packages/perennial-account/test/integration/Controller_Arbitrum.ts, packages/perennial-account/test/unit/Controller.ts, packages/perennial-account/test/unit/Verifier.ts
Added implementation logic to:
- Check whether a group may be rebalanced (intended to be called offchain).
- Perform a rebalance for a particular group.
Also:
- Tidy comments and sort _Controller_ methods.
- Corrected error signatures for recently-renamed errors.
=> Colateral Accounts - rebalance logic

packages/perennial-account/test/integration/Controller_Arbitrum.ts
this should fix Collateral Account integration tests
=> settle markets before rebalancing

packages/perennial-oracle/contracts/interfaces/IKeeperFactory.sol, packages/perennial-oracle/contracts/interfaces/IOracleFactory.sol
=> Fix function state mutability for interfaces

packages/perennial-oracle/contracts/payoff/Inverse.sol, packages/perennial-oracle/test/unit/payoff/Inverse.test.ts
We may need this payoff if we want to flip the base and quote currency for certain price feeds
=> Add 'Inverse' payoff

packages/perennial/contracts/Market.sol
=> [Code Size] Refactor update load / save calls to deduplicate logic

packages/common/testutil/types.ts, packages/perennial/contracts/Market.sol, packages/perennial/contracts/libs/CheckpointLib.sol, packages/perennial/contracts/libs/VersionLib.sol, packages/perennial/contracts/test/CheckpointTester.sol, packages/perennial/contracts/test/VersionTester.sol, packages/perennial/test/unit/types/Checkpoint.test.ts, packages/perennial/test/unit/types/Version.test.ts
=> [Code Size] Pass full context to accumulate libraries

packages/perennial/contracts/libs/CheckpointLib.sol, packages/perennial/contracts/types/Guarantee.sol
Clarifies solver fee logic, and resolves outstanding `TODO`s in the natspec.
=> [Docs] Add additional documentation on solver fee math

packages/perennial/contracts/MarketFactory.sol, packages/perennial/test/integration/core/happyPath.test.ts, packages/perennial/test/unit/marketfactory/MarketFactory.test.ts
Issue: https://github.com/sherlock-audit/2024-08-perennial-v2-update-3-judging/issues/54
=> Fix update extension

packages/perennial-extensions/contracts/Coordinator.sol, packages/perennial-extensions/test/unit/Coordinator/Coordinator.test.ts
Issue: https://github.com/sherlock-audit/2024-08-perennial-v2-update-3-judging/issues/24
=> Fix claim risk fee

packages/perennial-account/contracts/libs/RebalanceLib.sol, packages/perennial-account/contracts/types/RebalanceConfig.sol, packages/perennial-account/test/integration/Controller.ts
Fixes https://github.com/sherlock-audit/2024-08-perennial-v2-update-3-judging/issues/20
=> Fix issue rebalancing markets with no collateral

packages/perennial-account/contracts/Controller.sol, packages/perennial-account/contracts/libs/RebalanceLib.sol, packages/perennial-account/contracts/types/RebalanceConfig.sol, packages/perennial-account/contracts/types/RebalanceConfigChange.sol, packages/perennial-account/test/integration/Controller.ts, packages/perennial-account/test/integration/Controller_Arbitrum.ts, packages/perennial-account/test/unit/Controller.ts
Fixes https://github.com/sherlock-audit/2024-08-perennial-v2-update-3-judging/issues/84
Note this includes PR #447, a separate issue which affected the same code.
=> Fix potential donation attack rebalancing empty markets

packages/perennial-order/contracts/Manager.sol, packages/perennial-order/contracts/interfaces/IManager.sol, packages/perennial-order/test/integration/Manager_Arbitrum.test.ts, packages/perennial-order/test/unit/Manager.test.ts
Fixes https://github.com/sherlock-audit/2024-08-perennial-v2-update-3-judging/issues/79
=> Fix issue with users having ability to frontrun keeper maxFee

packages/perennial/contracts/MarketFactory.sol
Fixes https://github.com/sherlock-audit/2024-08-perennial-v2-update-3-judging/issues/53
=> [Fix] Re-organize MarketFactory slots for upgrade compatibility

packages/perennial/contracts/types/Position.sol
Fixes https://github.com/sherlock-audit/2024-08-perennial-v2-update-3-judging/issues/55
=> Fix Global position read/write with new slot format

packages/perennial-account/contracts/types/RebalanceConfigChange.sol
Fixes https://github.com/sherlock-audit/2024-08-perennial-v2-update-3-judging/issues/89
=> Remove unused code hashing RebalanceConfigChange

packages/perennial-vault/contracts/Vault.sol, packages/perennial-vault/contracts/types/Account.sol, packages/perennial-vault/test/integration/vault/Vault.test.ts
Fixes https://github.com/sherlock-audit/2024-08-perennial-v2-update-3-judging/issues/36
=> Fix Vault redemptionEligible calculation

packages/perennial-account/test/helpers/arbitrumHelpers.ts, packages/perennial-account/test/helpers/setupHelpers.ts, packages/perennial-deploy/tasks/multisig_ops/constants.ts, packages/perennial-deploy/util/constants.ts, packages/perennial-extensions/test/integration/helpers/setupHelpers.ts, packages/perennial-oracle/test/integration/metaquants/MetaQuantsOracleFactory.test.ts, packages/perennial-oracle/test/integration/pyth/PythOracleFactory.test.ts, packages/perennial-oracle/test/integrationSepolia/chainlink/ChainlinkOracleFactory.test.ts, packages/perennial-order/test/helpers/arbitrumHelpers.ts, packages/perennial/contracts/types/ProtocolParameter.sol, packages/perennial/contracts/types/RiskParameter.sol, packages/perennial/test/integration/helpers/setupHelpers.ts, packages/perennial/test/unit/market/Market.test.ts, packages/perennial/test/unit/marketfactory/MarketFactory.test.ts, packages/perennial/test/unit/types/Global.test.ts, packages/perennial/test/unit/types/MarketParameter.test.ts, packages/perennial/test/unit/types/ProtocolParameter.test.ts, packages/perennial/test/unit/types/RiskParameter.test.ts
Fixes https://github.com/sherlock-audit/2024-08-perennial-v2-update-3-judging/issues/58
=> Fix for coordinator setting staleAfter too high

packages/perennial/contracts/types/RiskParameter.sol, packages/perennial/test/unit/types/RiskParameter.test.ts
Reduces the severity of https://github.com/sherlock-audit/2024-08-perennial-v2-update-3-judging/issues/29
=> Fix maintenance and margin risk percentages which could be fat-fingered to high values

packages/perennial-extensions/contracts/MultiInvoker.sol, packages/perennial-extensions/test/unit/MultiInvoker/MultiInvoker.test.ts, packages/perennial-order/contracts/Manager.sol
Issue: https://github.com/sherlock-audit/2024-08-perennial-v2-update-3-judging/issues/35
=> Fix USDC unwrapping

packages/core/contracts/types/ProtocolParameter.sol, packages/core/contracts/types/RiskParameter.sol, packages/core/test/integration/core/happyPath.test.ts, packages/core/test/integration/helpers/setupHelpers.ts, packages/core/test/unit/types/Global.test.ts, packages/core/test/unit/types/MarketParameter.test.ts, packages/core/test/unit/types/ProtocolParameter.test.ts, packages/core/test/unit/types/RiskParameter.test.ts
Issue: https://linear.app/perennial/issue/PE-1978/[cleanup]-make-staleafter-uint16
=> Update `staleAfter` to uint16

packages/core/test/integration/core/happyPath.test.ts
Issue: https://linear.app/perennial/issue/PE-1980/multi-delayed-update-integration-test-failure
=> Fix multi-delayed update integration test 

packages/perennial-deploy/tasks/checkSolvency.ts, packages/perennial-deploy/tasks/settleMarkets.ts, packages/perennial-deploy/tasks/subgraphUtils.ts
Use new subgraph for Hardhat tasks
=> Update Subgraph URL to new Endpoint

packages/perennial/contracts/Market.sol, packages/perennial/contracts/interfaces/IMarket.sol, packages/perennial/contracts/test/OrderTester.sol, packages/perennial/contracts/types/Order.sol, packages/perennial/test/unit/market/Market.test.ts, packages/perennial/test/unit/types/Order.test.ts
Copied from: https://github.com/equilibria-xyz/perennial-v2/pull/491.
=> Add delta update for maker orders

.github/workflows/CI.yml, packages/perennial-order/test/integration/Manager_Arbitrum.test.ts
Resolve trigger order CI error running coverage on integration tests.
=> Adjust gas config

packages/periphery/test/integration/MultiInvoker/setupHelpers.ts, packages/vault/contracts/Vault.sol, packages/vault/contracts/VaultFactory.sol, packages/vault/contracts/interfaces/IVault.sol, packages/vault/contracts/interfaces/IVaultFactory.sol, packages/vault/contracts/libs/StrategyLib.sol, packages/vault/contracts/types/VaultParameter.sol, packages/vault/test/integration/vault/Vault.test.ts, packages/vault/test/unit/types/VaultParameter.test.ts
Issue: https://linear.app/perennial/issue/PE-610/[feature]-parameterized-leverage-buffer-in-vault
=> Parameterized leverage buffer in vault

packages/core/contracts/Margin.sol, packages/core/contracts/Market.sol, packages/core/contracts/interfaces/IMargin.sol, packages/core/test/integration/core/crossMargin.test.ts, packages/core/test/integration/core/happyPath.test.ts, packages/core/test/integration/helpers/setupHelpers.ts, packages/core/test/unit/margin/Margin.test.ts, packages/core/test/unit/market/Market.test.ts
This implements collections for tracking and iterating through cross-margined markets, along with logic for cross-margin margin and maintenance checks.  This includes changes to iterate through guarantees to aggregate price adjustments, a facility which should be in place before merging v2.4 audit fixes, such that effective collateral and worst-case position may be implemented appropriately.
=> Cross-margin logic

packages/vault/test/integration/vault/SolverVault.test.ts
Issue: https://linear.app/perennial/issue/PE-2149/[testing]-add-liquidation-and-insolvency-integration-tests-to
=> SolverVault liquidation and insolvency integration tests

packages/core/test/unit/types/Version.test.ts
Issue: https://linear.app/perennial/issue/PE-2060/[testing]-add-versionlib-test-for-accumulatetradefee
=> Unit tests for `_accumulateFees` in `VersionLib`

packages/core/contracts/libs/VersionLib.sol
Issue: https://linear.app/perennial/issue/PE-1962/[cleanup]-remove-interface-fees-claimable-from-multiinvoker
=> [Docs] Fix versionLib natspec

packages/core/contracts/Market.sol, packages/core/contracts/types/Take.sol, packages/core/test/helpers/erc712.ts, packages/core/test/integration/core/happyPath.test.ts, packages/core/test/unit/market/Market.test.ts
Issue: https://linear.app/perennial/issue/PE-2302/[feature]-support-additivefee-in-take-update
=> Add additive fee to update take

packages/core/test/unit/market/Market.test.ts
This is quite incomplete, but figured there may be value merging yesterday's work before abandoning the task for more important endeavors.
=> Add some pending order checks to Market checks

.github/workflows/CI.yml, packages/core/hardhat.config.ts, packages/core/package.json, packages/core/test/integrationPerennial/DeployedMarket.test.ts, packages/core/test/integrationPerennial/setupHelpers.ts
Tests run on a production fork at the current block height.  Useful for production debugging.  Facilities within will be referenced in support runbook documentation.
=> Live tests
